"""create UpdatePassword

Revision ID: b6a2ee5b1b8c
Revises: c0ee8f8b957b
Create Date: 2025-12-12 21:39:25.890174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a2ee5b1b8c'
down_revision: Union[str, Sequence[str], None] = 'c0ee8f8b957b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
